name: Daily Build

on:
  schedule:
    - cron: "30 22 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
    - name: Set up Poetry
      run: pip install poetry poethepoet poetry-dynamic-versioning[plugin]
    - name: Validate
      run: poe ci-latest
